### ISSUE TITLE
Add new column to tables

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/iso-data#7]
@jan-abel-inwt As discussed, we need one new column in several tables on the server. Please add a new _first_ column 
```sql
`mappingId` varchar(50) NOT NULL
```
to following tables: ` extraCharacter, extraNumeric, mapping, updated, warning`. 
For all rows the value of this column should be "IsoMemo" as it is used within the app right now:

![image](https://user-images.githubusercontent.com/16759098/221851816-b4cc83dd-942d-457f-93d9-0891b9480b7c.png)

Additionally, can you already now make a copy of the table `data` with the new name "IsoMemo_data". Then I can update the ETL respectively.

Can you check if the tables mentioned above are all that you can see on the server? That is, if we have not overseen something? Thanks!

I will add respective entries to the `schema.sql` in the repo.

_Originally posted by @arunge in https://github.com/Pandora-IsoMemo/iso-data/issues/4#issuecomment-1448096134_

**Comment by jan-abel-inwt** [comment]
## Add new column

```sql
# Add new column
ALTER TABLE mpiIso.extraCharacter
ADD `mappingId` varchar(50) NOT NULL;

ALTER TABLE mpiIso.extraNumeric
ADD `mappingId` varchar(50) NOT NULL;

ALTER TABLE mpiIso.mapping
ADD `mappingId` varchar(50) NOT NULL;

ALTER TABLE mpiIso.updated
ADD `mappingId` varchar(50) NOT NULL;

ALTER TABLE mpiIso.warning
ADD `mappingId` varchar(50) NOT NULL;

# Fill new column with key value
UPDATE mpiIso.extraCharacter
SET mappingId = "IsoMemo";

UPDATE mpiIso.extraNumeric 
SET mappingId = "IsoMemo";

UPDATE mpiIso.mapping 
SET mappingId = "IsoMemo";

UPDATE mpiIso.updated 
SET mappingId = "IsoMemo";

UPDATE mpiIso.warning 
SET mappingId = "IsoMemo";
```

## copy data table


```sql
USE mpiIso;

# Empty table with same structure
CREATE TABLE IsoMemo_data LIKE mpiIso.data;

# Copy data
INSERT INTO IsoMemo_data
SELECT *
FROM data;
```
